#!/usr/bin/env python3
"""Render YuE2 semantic tokens generated by the RWKV model (scripts/rwkv_generate.py) through YuE2 NAR (+ our R2 LoRA) + VAE
(PLAN §8.6 G3 gate). For each <gen>/<id>/semantic.npy writes <gen>/<id>/audio_<tag>.flac and, when --eval-root has a
directory for the same id (out/yue2_roundtrip_s2 with A_original.flac), also <eval-root>/<id>/C_roundtrip_<tag>.flac so
tools/yue2_roundtrip_eval.py scores it against the real Suno song (WER vs lyrics / vs original, MERT cosine).
Run inside venvs/yue2 on one GPU (~12 GiB).
usage: yue2_render_tokens.py --gen out/gen/final_s2 [--nar-lora out/joint/v2/lora_best.pt] [--tag rwkv_final] [--steps 32] [--eval-root out/yue2_roundtrip_s2]
"""
import argparse, json, sys, time
from pathlib import Path
import numpy as np, soundfile as sf, torch

ROOT = Path(__file__).resolve().parents[1]
YUE2 = ROOT / "models/yue2"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gen", required=True); ap.add_argument("--nar-lora", default=str(ROOT / "out/joint/v2/lora_best.pt"))
    ap.add_argument("--tag", default="rwkv"); ap.add_argument("--steps", type=int, default=32); ap.add_argument("--seed", type=int, default=4242)
    ap.add_argument("--eval-root", default=""); ap.add_argument("--vae", default="YuE2-Vae"); ap.add_argument("--max-frames", type=int, default=7500)
    args = ap.parse_args(); dev = "cuda"; gen = Path(args.gen); tag = f"{args.tag}_s{args.steps}"
    from yue2.modeling_yue2 import YuE2ForCausalLM
    from yue2.protocol import SongRequest, token_prefixes
    from yue2.tokenization_yue2 import YuE2TextTokenizer
    from yue2.nar import synthesize
    from yue2.modeling_vae import YuE2VAE
    items = []
    for d in sorted(p for p in gen.iterdir() if p.is_dir() and (p / "semantic.npy").exists()):
        if (d / f"audio_{tag}.flac").exists(): continue
        r = json.load(open(d / "request.json")); codes = np.load(d / "semantic.npy").astype(np.int64)[:args.max_frames]
        if len(codes) < 25: print(f"  skip {d.name}: {len(codes)} codes", flush=True); continue
        items.append(dict(dir=d, id=d.name, req=r, codes=codes))
    print(f"{len(items)} songs to render, NAR tag {tag}", flush=True); t0 = time.time()
    snap = str(YUE2 / "YuE2-3B")
    model = YuE2ForCausalLM.from_pretrained(snap, local_files_only=True, torch_dtype=torch.bfloat16, low_cpu_mem_usage=True).eval().to(dev)
    model.requires_grad_(False); bb = model.model; tok = YuE2TextTokenizer(snap + "/qwen.tiktoken")
    if args.nar_lora != "none":
        ck = torch.load(args.nar_lora, map_location=dev); it_ = iter(ck["lora"]); n_merged = 0
        with torch.no_grad():
            for layer in bb.layers:
                for mod, names in ((layer.nar_self_attn, ("q_proj", "k_proj", "v_proj", "o_proj")), (layer.nar_mlp, ("gate_proj", "up_proj", "down_proj"))):
                    for nme in names:
                        A = next(it_).to(dev).float(); B = next(it_).to(dev).float(); lin = getattr(mod, nme)
                        lin.weight.add_((B @ A).to(lin.weight.dtype)); n_merged += 1
            model.vae2llm.load_state_dict({k: v.to(torch.bfloat16) for k, v in ck["io"]["vae2llm"].items()})
            model.llm2vae.load_state_dict({k: v.to(torch.bfloat16) for k, v in ck["io"]["llm2vae"].items()})
        print(f"merged {n_merged} NAR LoRA linears + vae2llm/llm2vae", flush=True)
    for it in items:
        r = it["req"]; style = r.get("style") or "pop"; lyrics = (r.get("lyrics") or "").strip() or "[instrumental]"
        prefix = token_prefixes(SongRequest(style=style, lyrics=lyrics, cot="off", seed=1, id=it["id"]), tok)
        with torch.inference_mode():
            z = synthesize(model, prefix, [int(v) for v in it["codes"]], args.seed, steps=args.steps).float().cpu().numpy()
        it["lat"] = z; np.save(it["dir"] / f"latent_{tag}.npy", z.astype(np.float16))
        print(f"  NAR {it['id']} prefix {len(prefix)} codes {len(it['codes'])} -> latent {z.shape} {time.time() - t0:.0f}s", flush=True)
    del model; torch.cuda.empty_cache()
    vae = YuE2VAE.from_pretrained(str(YUE2 / args.vae), decoder_only=True, device=dev, local_files_only=True)
    for it in items:
        with torch.inference_mode():
            audio = vae.decode_tiled(torch.tensor(it["lat"].T[None]).contiguous(), core_frames=750, halo_frames=16, output_device="cpu")
        wav = audio[0].float().clamp(-1, 1).T.numpy()
        sf.write(it["dir"] / f"audio_{tag}.flac", wav, 48000, subtype="PCM_16")
        if args.eval_root and (Path(args.eval_root) / it["id"]).is_dir():
            sf.write(Path(args.eval_root) / it["id"] / f"C_roundtrip_{tag}.flac", wav, 48000, subtype="PCM_16")
    print(f"RENDER DONE {len(items)} songs in {time.time() - t0:.0f}s", flush=True)


if __name__ == "__main__":
    main()
